### ISSUE TITLE
build fails on gcc

### ISSUE THREAD

**Issue by chipitsine** [vtest/VTest#12]
https://travis-ci.org/chipitsine/haproxy-1/jobs/520502952

```
src/vtc_main.c: In function ‘cleaner_setup’:
src/vtc_main.c:231:3: error: ignoring return value of ‘nice’, declared with attribute warn_unused_result [-Werror=unused-result]
   (void)nice(1);  /* Not important */
   ^
```

**Comment by chipitsine** [comment]
knock-knock ?

**Comment by bsdphk** [comment]
I really don't know what to do about this one, except question the sanity of the people who think they get to decide if I can ignore the return value of nice(2) or not.

I explicitly put (void) on the return value of nice(2) because I, the programmer designing and writing the code, decided, as the comment also indicates, that it is not important if the nice call works or not.

I could possibly understand the warning if I had just not done anything about the return value...

**Comment by chipitsine** [comment]
personally, I did not mean modifying code.
can we adjust Makefile (to include some "please, shut up, gcc, just compile it" option) ?

**Comment by chipitsine** [comment]
I'll send PR on that

**Comment by tmccombs** [comment]
It looks like doing something like:

```
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wunused-result"
        (void)nice(1);        /* Not important */
#pragma GCC diagnostic pop
```
get the build to succeed with gcc.
