### ISSUE TITLE
VTest assert on Ubuntu 20.04 / s390

### ISSUE THREAD

**Issue by chipitsine** [vtest/VTest#20]
https://travis-ci.com/github/chipitsine/haproxy/jobs/366958312#L623

`---- c2   Assert error in vtc_gunzip(), src/vtc_gzip.c line 114:  Condition(vz.total_out < l) not true.  Errno=0 Success`

**Comment by daghf** [comment]
On gunzip varnishtest will set up an output buffer 10x the size of the input. If the decompressed content exceeds that, we hit this assert.

This is a known limitation, and we should perhaps print an error instead of asserting.

See https://github.com/vtest/VTest/blob/master/src/vtc_gzip.c#L105

**Comment by bsdphk** [comment]
I've been looking at this all morning, and it is slightly worse than that, because we assume the passed in buffer can contain the gunzip'ed data without any length-check, and while that generally is very probable from vtc_http.c, the way vtc_http2.c manages ->body leaves a lot less room.

This will have to be fixed properly.

**Comment by chipitsine** [comment]
thank you, guys.

I paused upgrading to ubuntu 20.04 for a while. Hope to get back to it soon

**Comment by bsdphk** [comment]
I have committed a fix varnish cache which solves the "times ten" issue, but not the "dont worry, of course the buffer is big enough" part.  Once it has been tested a bit, I'll merge it to VTEST

**Comment by chipitsine** [comment]
good good good!

I'll try haproxy vtest on ubuntu 20.04 soon
